/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.2/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
    
    // 🔴 Plugin JaCoCo para code coverage
    jacoco
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("com.github.ajalt.clikt:clikt:5.1.0")
    implementation("com.github.ajalt.mordant:mordant:3.0.2")
    implementation("com.github.ajalt.mordant:mordant-jvm:3.0.2")
    implementation("com.github.ajalt.mordant:mordant-jvm-jna:3.0.2")
    implementation("org.mindrot:jbcrypt:0.4")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
             useJUnit("4.13.2")
            dependencies {
                implementation(libs.mockk)
            }
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.bankaccount.console.AppKt"
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

// ============================================
// 🔴 CONFIGURATION JACOCO - CODE COVERAGE
// ============================================

jacoco {
    toolVersion = "0.8.11"
}

// Tarea para generar reporte HTML de JaCoCo
tasks.named<Test>("test") {
    finalizedBy("jacocoTestReport")
}

tasks.named<JacocoReport>("jacocoTestReport") {
    dependsOn("test")
    description = "Generate JaCoCo code coverage report after running tests"
    
    // Archivos fuente
    sourceDirectories.setFrom(sourceSets["main"].allSource.sourceDirectories)
    classDirectories.setFrom(files(sourceSets["main"].output.classesDirs))
    executionData.setFrom(files(layout.buildDirectory.file("jacoco/test.exec")))
    
    reports {
        xml.required.set(true)
        html.required.set(true)
        csv.required.set(false)
    }
    
    doLast {
        println("\n" + "=".repeat(60))
        println("📊 REPORT GENERATED SUCCESSFULLY")
        println("=".repeat(60))
        println("📄 Open in the browser:")
        println("   ${layout.buildDirectory.get()}/reports/jacoco/test/html/index.html")
        println("=".repeat(60))
    }
}


tasks.register("verifyCodeCoverage") {
    dependsOn("jacocoTestReport")
    description = "Verify that code coverage is >= 80%"
    
    doLast {
        val reportFile = file("${layout.buildDirectory.get()}/reports/jacoco/test/jacocoTestReport.xml")
        
        if (!reportFile.exists()) {
            throw GradleException("❌ JaCoCo report not found. Please run: ./gradlew test jacocoTestReport")
        }
        
        val xml = reportFile.readText()
        
        // Parsear cobertura de líneas
        val lineRateRegex = """<counter type="LINE"[^>]*covered="(\d+)"[^>]*missed="(\d+)"""".toRegex()
        val match = lineRateRegex.find(xml)
        
        if (match != null) {
            val covered = match.groupValues[1].toInt()
            val missed = match.groupValues[2].toInt()
            val total = covered + missed
            val percentage = if (total > 0) (covered * 100) / total else 0
            
            println("\n" + "=".repeat(60))
            println("📊 CODE COVERAGE REPORT")
            println("=".repeat(60))
            println("✅ Lines Covered:    $covered")
            println("❌ Lines Not Covered: $missed")
            println("📈 Total Lines:     $total")
            println("💯 Percentage:          $percentage%")
            println("🎯 Minimum Required:    80%")
            println("=".repeat(60))
            
            if (percentage < 80) {
                println("\n🚨 ERROR: The coverage ($percentage%) is below the required 80%")
                println("📄 Open the report in the browser: ${layout.buildDirectory.get()}/reports/jacoco/test/html/index.html")
                throw GradleException("❌ Code coverage below the required 80% ($percentage%)")
            } else {
                println("\n✨ Valid code coverage! ($percentage% >= 80%)")
            }
        } else {
            println("\n⚠️  Warning: Could not parse coverage from XML")
        }
    }
}
